/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 14-zĂˇĹ™-2022 12:20:30 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS t_bmi CASCADE
;

DROP TABLE IF EXISTS t_cat CASCADE
;

DROP TABLE IF EXISTS t_country CASCADE
;

DROP TABLE IF EXISTS t_disasters CASCADE
;

DROP TABLE IF EXISTS t_dog CASCADE
;

DROP TABLE IF EXISTS t_education CASCADE
;

DROP TABLE IF EXISTS t_female_labour CASCADE
;

DROP TABLE IF EXISTS t_fertility_rate CASCADE
;

DROP TABLE IF EXISTS t_infertility CASCADE
;

DROP TABLE IF EXISTS "t_IVF" CASCADE
;

DROP TABLE IF EXISTS t_p10_vs_p90 CASCADE
;

DROP TABLE IF EXISTS t_urban CASCADE
;

DROP TABLE IF EXISTS t_working_hours CASCADE
;

/* Create Tables */

CREATE TABLE t_bmi
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	"Mean BMI (female)" numeric(20,5) NULL
)
;

CREATE TABLE t_cat
(
	id bigint NOT NULL,
	country varchar(100) NULL,
	year bigint NULL,
	cat numeric(20,5) NULL
)
;

CREATE TABLE t_country
(
	tablename varchar(100) NOT NULL,
	"Country Code" varchar(10) NOT NULL,
	region varchar(50) NULL,
	incomegroup varchar(50) NULL,
	specialnotes varchar(1000) NULL
)
;

CREATE TABLE t_disasters
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	deaths numeric(20,5) NULL
)
;

CREATE TABLE t_dog
(
	id bigint NOT NULL,
	country varchar(100) NULL,
	year bigint NULL,
	dog numeric(20,5) NULL
)
;

CREATE TABLE t_education
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	"Average Total Years of Schooling" numeric(20,5) NULL
)
;

CREATE TABLE t_female_labour
(
	"Country Name" varchar(100) NULL,
	"Country Code" varchar(10) NULL,
	"Indicator Name" varchar(100) NULL,
	"Indicator Code" varchar(32) NULL,
	r1960 numeric(20,5) NULL,
	r1961 numeric(20,5) NULL,
	r1962 numeric(20,5) NULL,
	r1963 numeric(20,5) NULL,
	r1964 numeric(20,5) NULL,
	r1965 numeric(20,5) NULL,
	r1966 numeric(20,5) NULL,
	r1967 numeric(20,5) NULL,
	r1968 numeric(20,5) NULL,
	r1969 numeric(20,5) NULL,
	r1970 numeric(20,5) NULL,
	r1971 numeric(20,5) NULL,
	r1972 numeric(20,5) NULL,
	r1973 numeric(20,5) NULL,
	r1974 numeric(20,5) NULL,
	r1975 numeric(20,5) NULL,
	r1976 numeric(20,5) NULL,
	r1977 numeric(20,5) NULL,
	r1978 numeric(20,5) NULL,
	r1979 numeric(20,5) NULL,
	r1980 numeric(20,5) NULL,
	r1981 numeric(20,5) NULL,
	r1982 numeric(20,5) NULL,
	r1983 numeric(20,5) NULL,
	r1984 numeric(20,5) NULL,
	r1985 numeric(20,5) NULL,
	r1986 numeric(20,5) NULL,
	r1987 numeric(20,5) NULL,
	r1988 numeric(20,5) NULL,
	r1989 numeric(20,5) NULL,
	r1990 numeric(20,5) NULL,
	r1991 numeric(20,5) NULL,
	r1992 numeric(20,5) NULL,
	r1993 numeric(20,5) NULL,
	r1994 numeric(20,5) NULL,
	r1995 numeric(20,5) NULL,
	r1996 numeric(20,5) NULL,
	r1997 numeric(20,5) NULL,
	r1998 numeric(20,5) NULL,
	r1999 numeric(20,5) NULL,
	r2000 numeric(20,5) NULL,
	r2001 numeric(20,5) NULL,
	r2002 numeric(20,5) NULL,
	r2003 numeric(20,5) NULL,
	r2004 numeric(20,5) NULL,
	r2005 numeric(20,5) NULL,
	r2006 numeric(20,5) NULL,
	r2007 numeric(20,5) NULL,
	r2008 numeric(20,5) NULL,
	r2009 numeric(20,5) NULL,
	r2010 numeric(20,5) NULL,
	r2011 numeric(20,5) NULL,
	r2012 numeric(20,5) NULL,
	r2013 numeric(20,5) NULL,
	r2014 numeric(20,5) NULL,
	r2015 numeric(20,5) NULL,
	r2016 numeric(20,5) NULL,
	r2017 numeric(20,5) NULL,
	r2018 numeric(20,5) NULL,
	r2019 numeric(20,5) NULL,
	r2020 numeric(20,5) NULL,
	r2021 numeric(20,5) NULL
)
;

CREATE TABLE t_fertility_rate
(
	"Country or Area" varchar(100) NOT NULL,
	"Country or Area Code" varchar(10) NULL,
	"Age Group" varchar(20) NULL,
	indicator varchar(20) NULL,
	date bigint NOT NULL,
	value numeric(20,5) NULL,
	datatype varchar(100) NULL,
	"Data Source Type" varchar(20) NULL,
	"Survey Programme" varchar(100) NULL,
	"Data Source Inventory ID" integer NULL,
	"Data Source Name" varchar(200) NULL,
	"Data Source Name (short)" varchar(50) NULL,
	"Data Source Start Year" varchar(50) NULL,
	"Data Source End Year" varchar(50) NULL,
	reference varchar(500) NULL,
	"Reference Year" integer NULL,
	series varchar(300) NULL
)
;

CREATE TABLE t_infertility
(
	id bigint NOT NULL,
	country varchar(100) NULL,
	year bigint NULL,
	infertility numeric(20,5) NULL
)
;

CREATE TABLE "t_IVF"
(
	id bigint NOT NULL,
	country varchar(100) NULL,
	year bigint NULL,
	ivf numeric(20,5) NULL
)
;

CREATE TABLE t_p10_vs_p90
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	"p90 of income/consumption distribution" numeric(20,5) NULL,
	"p10 of income/consumption distribution" numeric(20,5) NULL,
	"World Bank region (for p10/90 data)" varchar(50) NULL
)
;

CREATE TABLE t_urban
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	"Urban population" bigint NULL,
	"Rural population" bigint NULL,
	ratio numeric(20,5) NULL
)
;

CREATE TABLE t_working_hours
(
	entity varchar(100) NULL,
	code varchar(10) NULL,
	year bigint NULL,
	"Average annual working hours per worker" numeric(20,5) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */


ALTER TABLE t_cat ADD CONSTRAINT "PK_t_cat"
	PRIMARY KEY (id)
;



ALTER TABLE t_dog ADD CONSTRAINT "PK_t_dog"
	PRIMARY KEY (id)
;


ALTER TABLE t_infertility ADD CONSTRAINT "PK_t_infertility"
	PRIMARY KEY (id)
;

ALTER TABLE "t_IVF" ADD CONSTRAINT "PK_t_IVF"
	PRIMARY KEY (id)
;

