/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 14-zĂˇĹ™-2022 12:24:04 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS t_correlants CASCADE
;

DROP TABLE IF EXISTS t_country CASCADE
;

DROP TABLE IF EXISTS t_fertility_rate CASCADE
;

/* Create Tables */

CREATE TABLE t_correlants
(
	id bigint NULL,
	name varchar(50) NULL,
	date bigint NULL,
	country varchar(100) NULL,
	value numeric(20,5) NULL,
	tk bigint NOT NULL,
	version integer NULL,
	date_from timestamp without time zone NULL,
	date_to timestamp without time zone NULL
)
;

CREATE TABLE t_country
(
	country varchar(100) NULL,
	region varchar(50) NULL,
	incomegroup varchar(50) NULL,
	tk bigint NOT NULL,
	version integer NULL,
	date_from timestamp without time zone NULL,
	date_to timestamp without time zone NULL,
	id bigint NULL
)
;

CREATE TABLE t_fertility_rate
(
	tk bigint NOT NULL,
	country varchar(100) NULL,
	date bigint NULL,
	tfr numeric(20,5) NULL,
	version integer NULL,
	date_from timestamp without time zone NULL,
	date_to timestamp without time zone NULL,
	id bigint NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE t_correlants ADD CONSTRAINT "PK_t_corelants"
	PRIMARY KEY (tk)
;

CREATE INDEX "IXFK_t_corelants_t_country" ON t_correlants (country ASC)
;

ALTER TABLE t_country ADD CONSTRAINT "PK_t_country"
	PRIMARY KEY (tk)
;

ALTER TABLE t_fertility_rate ADD CONSTRAINT "PK_t_fertility_rate"
	PRIMARY KEY (tk)
;

CREATE INDEX "IXFK_t_fertility_rate_t_country" ON t_fertility_rate (country ASC)
;
